name: Merge Schedule
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    - cron: 0 12 */2 * *

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v2
        with:
          merge_method: squash
          time_zone: 'Europe/Athens'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
